### ISSUE TITLE
LocationShowPage component does too much data handling in the .then of of the useEffect fetch request

### ISSUE THREAD

**Issue by nwalberts** [TheTedder/hotspots-site#27]
I realize that lines 35 through 50 have already been merged. But upon further review I noticed that the flow control you currently have in the above lines should have already been managed on the backend, ideally in a serializer. If the if statements relied on some current state or props this might be different, but given that you are just checking the returned data, we these items should already be sorted prior to the info reaching your front end.

**Comment by safang99** [comment]
Resolved
